### ISSUE TITLE
[Question] All firebase libraries must be either above or below 14.0.0

### ISSUE THREAD

**Issue by aikeda** [Pushwoosh/pushwoosh-android-sdk#135]
Hi all!

I'm trying to setup Pushwoosh v5.19 that requires [com.google.gms:firebase-messaging:11.6.0](https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/Samples/Android-Simple/build.gradle#L25). But I also need to use `com.google.android.gms:play-services-cast-framework:16.2.0`. Using both versions gives me an error when building: `ERROR: All firebase libraries must be either above or below 14.0.0` and I can't downgrade my google cast dependency. If I force to use a higher firebase-messaging version (14+) i get a runtime crash.

Any idea on how to handle this?

**Comment by wfhm** [comment]
Hi @aikeda,

Checking it

**Comment by wfhm** [comment]
@aikeda could you please confirm that this issue was resolved via the support channel?

Copying the message from the support thread for the future reference:

> Could you please try to use the 17.6.0 version of the firebase-messaging?  
It uses the same versions of gms libraries as the com.google.android.gms:play-services-cast-framework:16.2.0 so this solution may help to resolve the issue. 

> https://mvnrepository.com/artifact/com.google.firebase/firebase-messaging/17.6.0
https://mvnrepository.com/artifact/com.google.android.gms/play-services-cast-framework/16.2.0
