### ISSUE TITLE
How reset userId after logout

### ISSUE THREAD

**Issue by AnatolaKH** [Pushwoosh/pushwoosh-android-sdk#139]
**From documentation:**

Login/Logout behavior
By default, when an app with Pushwoosh SDK is launched for the first time, it sets a device HWID as a UserID. You can call setUserId on a login to set any required value to associate a device with a particular user. When a user logs out, you can reset this value to a default one with another setUserId call, e.g. to an initial HWID value.

How I can reset userId? Call method with empty string or hwid from SDK?

**Comment by wfhm** [comment]
Hello,

As per the documentation, simply call another `/setUserID` on logout and userID value will be reset to a default HWID value:


    (void)setUserId:(NSString *)userId //for iOS

    public void setUserId(java.lang.String userId) //for Android


Should you have any additional questions or concerns, please do not hesitate to contact us!

Kind regards,
Evgeny Starikov
Pushwoosh Team

**Comment by AnatolaKH** [comment]
> Hello,
> 
> As per the documentation, simply call another `/setUserID` on logout and userID value will be reset to a default HWID value:
> 
> ```
> (void)setUserId:(NSString *)userId //for iOS
> 
> public void setUserId(java.lang.String userId) //for Android
> ```
> 
> Should you have any additional questions or concerns, please do not hesitate to contact us!
> 
> Kind regards,
> Evgeny Starikov
> Pushwoosh Team

Hello,

If I want to set a new userId, I must call method twice? 
Will the first call "setUserId" be replaced with default HWID, and the second with a new one?

**Comment by wfhm** [comment]
In order to reset a userID to a new value it is not necessary to call `/setUserID` method twice - first /`setUserID`​ call on login will set a custom userID value and it will stay intact if you do not call another one on log out. Afterward, if you require to reset a UserID of a particular user you can call `/setUserID` manually, thus replacing it with a new value (not HWID).

However, in order to advise you more precisely on that matter, could you please describe your use-case in more detail?

I look forward to hearing from you soon!

Kind regards,
Evgeny Starikov
Pushwoosh Team

* * *
Please visit our **Help Center** where you can manage all your support requests and find solutions to the vast number of questions:

https://help.pushwoosh.com/hc/

**Comment by wfhm** [comment]
@AnatolaKH ,

I am sorry for the confusion caused by the previous responses. To set a new User ID, just call the method again with a new value. The value set with the first call will be replaced by the new one. If you want to just clear this value, i.e. on logout, just a value that is not linked to any user in your system, like device HWID.

**Comment by AnatolaKH** [comment]
@wfhm ,

thx you for answer
