### ISSUE TITLE
App Removal due to SDK

### ISSUE THREAD

**Issue by boredom2** [Pushwoosh/pushwoosh-android-sdk#159]
Hi there,

We received an Email today from Google App Store, which informed us about the removal of our app due to the PushWoosh SDK.

"We’ve identified that your app is using Pushwoosh SDK or library, which facilitates the transmission of collection of installed application without User Consent."

Is this correct? How can we stop this behaviour?
We are not using the latest version, but a quite recent version of the sdk. Has this behaviour been changed currently?

Thanks,
Christoph

**Comment by wfhm** [comment]
Hello Christoph,

You may receive a notification from Google stating that your Android app doesn’t meet the privacy policy or prominent disclosure requirements because your app is uploading the information on users’ installed applications via Pushwoosh SDK.

Older versions of Pushwoosh Android SDK (6.2.4 and below) had methods to query the list of installed packages on the device. As per the upcoming changes in the Developer program policy, it may require prominent disclosure and changes to the privacy policy to keep the application published.

We strongly recommend updating your SDK to the latest version (6.2.7 at the moment of publication) to meet the latest requirements from the Google Play Store.

**Comment by boredom2** [comment]
Thanks for your fast Reply. In other Words - this feature/functionality has been removed in >=6.2.5 and Google wont reject it again. Is this correct?

**Comment by boredom2** [comment]
And concerning this - it would be great if you could release the current Version also in the Cordova Plugin (this still uses 6.2.4). Im pretty sure I can use the latest Cordova Plugin with Version 6.2.7 anyway, but would be better to remove this also there.
Thanks a lot!

**Comment by wfhm** [comment]
@boredom2,

Sure, all plugins will be updated ASAP.

**Comment by ipehimanshu** [comment]
ok so we are using this plugin
pushwoosh-cordova-plugin so when it should be updated?
Because so far our 5 apps removed from google play store.

**Comment by wfhm** [comment]
@ipehimanshu, @boredom2

The new version of our Cordova plugin (8.1.1) is released, you can safely update and resubmit your apps to the Store now.

**Comment by HassanImtiaz** [comment]
Does this issue exists for 5.22.2?

**Comment by wfhm** [comment]
@HassanImtiaz yes, for Xamarin it was only fixed with 5.23.0
