### ISSUE TITLE
Test Device Showing as Unregistered

### ISSUE THREAD

**Issue by mpallansch** [Pushwoosh/pushwoosh-android-sdk#162]
I recently updated the version of the Pushwoosh SDK in my Android project to 6.2.5 to comply with Google Play's policy update. However when testing the new build, push notifications are not received. 

In the logcat I am seeing a successful registration:

`I/Pushwoosh: [DeviceRegistrar] Registered for push notifications: ....`

However, when using the token to register a test device and then send a test push, I see in the details of the message that the device is unregistered:

![Screenshot 2021-05-03 160412](https://user-images.githubusercontent.com/6432735/116927118-3e12fb00-ac29-11eb-8044-3e4fbb560233.png)

In this documentation (https://help.pushwoosh.com/hc/en-us/articles/360000509326-Push-Reports-explained) I don't see an explanation for "Unregistered" status for the Android platform.

**Comment by wfhm** [comment]
@mpallansch,

The **Unregistered** is the response we get from FCM that means a push token is no longer valid. It usually happens when a user uninstalls your app, however, FCM tokens can change from time to time. In this case, you should update a push token in the Test Devices tab manually.

You can find the actual token in device console logs (search for /registerDevice API request) or obtain it programmatically with the getPushToken() method.

Could it be that you did not update a push token after reinstalling your app on the test device?

**Comment by mpallansch** [comment]
Thank you for the quick reply. 

This was a new test device for the account, registered only with the updated build. I pushed the build to the device, got the token from the logcat, entered it into the Pushwoosh console, and send a test push. The build was not uninstalled at the time of the test push.

> @mpallansch,
> 
> The **Unregistered** is the response we get from FCM that means a push token is no longer valid. It usually happens when a user uninstalls your app, however, FCM tokens can change from time to time. In this case, you should update a push token in the Test Devices tab manually.
> 
> You can find the actual token in device console logs (search for /registerDevice API request) or obtain it programmatically with the getPushToken() method.
> 
> Could it be that you did not update a push token after reinstalling your app on the test device?

**Comment by wfhm** [comment]
@mpallansch,

To avoid exposing sensitive data publicly, may I ask you to create a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new and your Application code and account name so we could check what happens with the test device?
