### ISSUE TITLE
Pushwoosh notification do not get when Android app is not running.

### ISSUE THREAD

**Issue by jondoes** [Pushwoosh/pushwoosh-android-sdk#50]
Hello,

I have followed this url [PushWoosh-Android](http://docs.pushwoosh.com/docs/android-sdk-fragments) to implement pushwoosh in android app.

but when I send message from pushwoosh CP, It will only get when App is running,
but not get when app is removed from recent or killed.

I want to display notification when App is not running, How can I do that ?

Thanks.

**Comment by wfhm** [comment]
Hi,

Android apps will never receive a push if it was killed via App manager, however if it was just swiped from Task Manager it should've worked. Could you please try our [Sample app](https://github.com/Pushwoosh/pushwoosh-android-sdk/tree/master/Samples/Android-Simple) and let us know if the issue is reproducible with it?

Could you please also check in your device logs whether or nto the app was force stopped?

**Comment by ikkifujiwara** [comment]
Hi,

Im using the phonegap sdk and i did raise this issue as well at https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/238

I also found that there are possible way to do that

http://www.concretepage.com/android/android-alarm-clock-tutorial-to-schedule-and-cancel-alarmmanager-pendingintent-and-wakefulbroadcastreceiver-example

https://developer.android.com/reference/android/support/v4/content/WakefulBroadcastReceiver.html

any idea how to implement this at here and phonegap sdk as well?

**Comment by shaders** [comment]
Pushwoosh SDK already implements WakefulBroadcastReceiver.

Regarding force-stopping the app see more here:
http://stackoverflow.com/questions/20838415/gcm-push-notification-works-after-app-force-stop

This behavior is there since Android 3.1
