### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by MostafaAryan** [Pushwoosh/pushwoosh-android-sdk#65]
Hi,
I have an android app on google play store, when i try to send push notifications on it, all of sent pushes are reported as "Unauthorized", this is happening while i can send push notifications to my test devices successfully.
What could be the problem?
I'm using a GCM Api key (which i think its functional as i can send test pushes successfully) and these are my project dependencies:
> compile 'com.pushwoosh:pushwoosh:4.10.8'
> compile "com.google.android.gms:play-services-gcm:10.2.4"

**Comment by wfhm** [comment]
Hi,

You should import your project to Firebase:

http://docs.pushwoosh.com/docs/fcm-configuration

This issue is related to Pushwoosh configuration, therefore please contact our Support team via the form below:

https://www.pushwoosh.com/contact-us/

They will provide you with detailed instructions on migrating your project to FCM and re-configuring your application in Pushwoosh Control Panel.
